version: "3"
services:
  client:
    image: sci-dict-client-i
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: sci-dict-client-c
    network_mode: "host"
    environment:
      - NODE_ENV=production
  backend:
    image: sci-dict-be-i
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: sci-dict-be-c
    ports:
      - "${PORT}:${PORT}" 
    environment:
      - PORT=${PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: sci-dict-db-c
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}